// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hospitalBackend.Data;

#nullable disable

namespace hospitalBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hospitalBackend.Models.Medico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = "dok1od21kod12",
                            ApellidoMaterno = "Pedraza",
                            ApellidoPaterno = "Moron",
                            Especialidad = "Cirujano",
                            Nombre = "Ismael"
                        },
                        new
                        {
                            Id = "123",
                            ApellidoMaterno = "Lopez",
                            ApellidoPaterno = "Perez",
                            Especialidad = "Pediatra",
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id = "321",
                            ApellidoMaterno = "Redes 2",
                            ApellidoPaterno = "Peredo",
                            Especialidad = "Docente",
                            Nombre = "Roberto"
                        },
                        new
                        {
                            Id = "1231",
                            ApellidoMaterno = "Duran",
                            ApellidoPaterno = "Mercado",
                            Especialidad = "Medico",
                            Nombre = "Cristian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
